language: php

php:
- 5.3
- 5.4
- 5.5
- 5.6
- hhvm

install:
  - composer install --verbose
  
before_script: 
- curl -sSL https://raw.githubusercontent.com/moliware/travis-solr/master/travis-solr.sh | SOLR_VERSION=4.10.3 bash
